    
server:
    servlet: 
      context-path: /phone-booking-service
management: 
  server: 
    port: 8081
    servlet: 
      context-path: /phone-booking-service
  endpoints: 
    web: 
      base-path: /
      
spring:
  datasource:
    url: jdbc:h2:mem:phone-booking;
    platform: h2
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

fonoapi: 
   url: https://fonoapi.freshpixl.com/v1/
     
      
    